
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DOISPONTOS INICIOPROD NOMECAT NUMERO PONTOVIRG REAL SEP TEXTOcategorias : categoriacategorias : categorias categoriacategoria : NOMECAT DOISPONTOS produtosprodutos : produto\n                | produtos produtoproduto : INICIOPROD NUMERO SEP TEXTO SEP REAL SEP NUMERO PONTOVIRG'
    
_lr_action_items = {'NOMECAT':([0,1,2,4,6,7,9,17,],[3,3,-1,-2,-3,-4,-5,-6,]),'$end':([1,2,4,6,7,9,17,],[0,-1,-2,-3,-4,-5,-6,]),'DOISPONTOS':([3,],[5,]),'INICIOPROD':([5,6,7,9,17,],[8,8,-4,-5,-6,]),'NUMERO':([8,15,],[10,16,]),'SEP':([10,12,14,],[11,13,15,]),'TEXTO':([11,],[12,]),'REAL':([13,],[14,]),'PONTOVIRG':([16,],[17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'categorias':([0,],[1,]),'categoria':([0,1,],[2,4,]),'produtos':([5,],[6,]),'produto':([5,6,],[7,9,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> categorias","S'",1,None,None,None),
  ('categorias -> categoria','categorias',1,'p_categorias_categoria','comprasProf.py',113),
  ('categorias -> categorias categoria','categorias',2,'p_categorias_categorias','comprasProf.py',117),
  ('categoria -> NOMECAT DOISPONTOS produtos','categoria',3,'p_categoria','comprasProf.py',124),
  ('produtos -> produto','produtos',1,'p_produtos','comprasProf.py',131),
  ('produtos -> produtos produto','produtos',2,'p_produtos','comprasProf.py',132),
  ('produto -> INICIOPROD NUMERO SEP TEXTO SEP REAL SEP NUMERO PONTOVIRG','produto',9,'p_produto','comprasProf.py',139),
]
