
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'AND EQUIV IMPL LETRA LPAR NOT OR RPARpred : pred AND predpred : pred OR predpred : NOT predpred : pred IMPL predpred : pred EQUIV predpred : LPAR pred RPARpred : LETRA'
    
_lr_action_items = {'NOT':([0,2,3,5,6,7,8,],[2,2,2,2,2,2,2,]),'LPAR':([0,2,3,5,6,7,8,],[3,3,3,3,3,3,3,]),'LETRA':([0,2,3,5,6,7,8,],[4,4,4,4,4,4,4,]),'$end':([1,4,9,11,12,13,14,15,],[0,-7,-3,-1,-2,-4,-5,-6,]),'AND':([1,4,9,10,11,12,13,14,15,],[5,-7,5,5,5,5,5,5,-6,]),'OR':([1,4,9,10,11,12,13,14,15,],[6,-7,6,6,6,6,6,6,-6,]),'IMPL':([1,4,9,10,11,12,13,14,15,],[7,-7,7,7,7,7,7,7,-6,]),'EQUIV':([1,4,9,10,11,12,13,14,15,],[8,-7,8,8,8,8,8,8,-6,]),'RPAR':([4,9,10,11,12,13,14,15,],[-7,-3,15,-1,-2,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'pred':([0,2,3,5,6,7,8,],[1,9,10,11,12,13,14,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> pred","S'",1,None,None,None),
  ('pred -> pred AND pred','pred',3,'p_pred_and','logicaProf.py',9),
  ('pred -> pred OR pred','pred',3,'p_pred_or','logicaProf.py',13),
  ('pred -> NOT pred','pred',2,'p_pred_not','logicaProf.py',17),
  ('pred -> pred IMPL pred','pred',3,'p_pred_impl','logicaProf.py',21),
  ('pred -> pred EQUIV pred','pred',3,'p_pred_equiv','logicaProf.py',25),
  ('pred -> LPAR pred RPAR','pred',3,'p_pred_pars','logicaProf.py',29),
  ('pred -> LETRA','pred',1,'p_pred_letra','logicaProf.py',33),
]
